In [8]:
import pandas as pd

In [9]:
review = "C:\\Users\\gasty\\Desktop\\PF\\Yelp\\user-003.parquet"

In [12]:
user_003 = pd.read_parquet(review)

In [13]:
user_003

,user_id,name,review_count,yelping_since,useful,funny,cool,elite,friends,fans,...,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos
0,qVc8ODYU5SZjKXVBgXdI7w,Walker,585,2007-01-25 16:47:26,7217,1259,5994,2007,"NSCy54eWehBJyZdG2iE84w, pe42u7DcCH2QmI81NX-8qA...",267,...,65,55,56,18,232,844,467,467,239,180
1,j14WgRoU_-2ZE1aw1dXrJg,Daniel,4333,2009-01-25 04:35:42,43091,13066,27281,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2...","ueRPE0CX75ePGMqOFVj6IQ, 52oH4DrRvzzl8wh5UXyU0A...",3138,...,264,184,157,251,1847,7054,3131,3131,1521,1946
2,2WnXYQFK0hXEoTxPtV2zvg,Steph,665,2008-07-25 10:41:00,2086,1010,1003,"2009,2010,2011,2012,2013","LuO3Bn4f3rlhyHIaNfTlnA, j9B4XdHUhDfTKVecyWQgyA...",52,...,13,10,17,3,66,96,119,119,35,18
3,SZDeASXq7o05mMNLshsdIA,Gwen,224,2005-11-29 04:38:33,512,330,299,"2009,2010,2011","enx1vVPnfdNUdPho6PH_wg, 4wOcvMLtU6a9Lslggq74Vg...",28,...,4,1,6,2,12,16,26,26,10,9
4,hA5lMy-EnncsH4JoR-hFGQ,Karen,79,2007-01-05 19:40:59,29,15,7,,"PBK4q9KEEBHhFvSXCUirIw, 3FWPpM7KU1gXeOM_ZbYMbA...",1,...,1,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2105592,4QGxxakRZeOlg_qDuxmTeQ,Jennilee,38,2012-01-19 23:33:02,74,9,6,,kmwNG5LZSHFmveg6wYYdrw,0,...,1,0,0,0,1,4,0,0,1,0
2105593,tmelBbVBGAzXBVfH2u_R6g,Gerry,19,2009-06-09 16:34:54,14,5,2,,"BFYdCAMFyjYHDwesndEXEg, _9fTIqfSJc7g3V_o76XRVg...",1,...,1,0,0,0,0,1,0,0,0,0
2105594,tpBznnD6uJN3m_pJubj09w,Emily,26,2013-08-13 23:18:11,4,1,2,,"bKV3ly2MuK-K1cptMrFknQ, liel18zRoSB4tEkUP7i6Cg...",0,...,0,0,0,0,1,0,0,0,0,0
2105595,Kst_srPw7GdYydMFYdCtzw,Heatheranne,25,2015-01-10 00:06:25,21,2,5,,"dzHTk52vbGtbktRm_B-wEg, fOfFLV7IbBDN6lzARaLqdg...",0,...,0,0,0,0,0,1,0,0,0,0
2105596,mZl-mH3ZIWLRSd_FfvrXFg,Jessica,30,2015-11-30 21:10:17,27,1,17,,"pou3BbKsIozfH50rxmnMew, JT3rDC7-hprCSObnihMeHw...",3,...,0,1,0,0,0,1,0,0,1,0

In [14]:
print(user_003.shape)
user_003.head()

(2105597, 22)

,user_id,name,review_count,yelping_since,useful,funny,cool,elite,friends,fans,...,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos
0,qVc8ODYU5SZjKXVBgXdI7w,Walker,585,2007-01-25 16:47:26,7217,1259,5994,2007,"NSCy54eWehBJyZdG2iE84w, pe42u7DcCH2QmI81NX-8qA...",267,...,65,55,56,18,232,844,467,467,239,180
1,j14WgRoU_-2ZE1aw1dXrJg,Daniel,4333,2009-01-25 04:35:42,43091,13066,27281,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2...","ueRPE0CX75ePGMqOFVj6IQ, 52oH4DrRvzzl8wh5UXyU0A...",3138,...,264,184,157,251,1847,7054,3131,3131,1521,1946
2,2WnXYQFK0hXEoTxPtV2zvg,Steph,665,2008-07-25 10:41:00,2086,1010,1003,"2009,2010,2011,2012,2013","LuO3Bn4f3rlhyHIaNfTlnA, j9B4XdHUhDfTKVecyWQgyA...",52,...,13,10,17,3,66,96,119,119,35,18
3,SZDeASXq7o05mMNLshsdIA,Gwen,224,2005-11-29 04:38:33,512,330,299,"2009,2010,2011","enx1vVPnfdNUdPho6PH_wg, 4wOcvMLtU6a9Lslggq74Vg...",28,...,4,1,6,2,12,16,26,26,10,9
4,hA5lMy-EnncsH4JoR-hFGQ,Karen,79,2007-01-05 19:40:59,29,15,7,,"PBK4q9KEEBHhFvSXCUirIw, 3FWPpM7KU1gXeOM_ZbYMbA...",1,...,1,0,0,0,1,1,0,0,0,0

In [15]:
user_003.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2105597 entries, 0 to 2105596
Data columns (total 22 columns):
 #   Column              Dtype
---  ------              -----
 0   user_id             object
 1   name                object
 2   review_count        int64
 3   yelping_since       object
 4   useful              int64
 5   funny               int64
 6   cool                int64
 7   elite               object
 8   friends             object
 9   fans                int64
 10  average_stars       float64
 11  compliment_hot      int64
 12  compliment_more     int64
 13  compliment_profile  int64
 14  compliment_cute     int64
 15  compliment_list     int64
 16  compliment_note     int64
 17  compliment_plain    int64
 18  compliment_cool     int64
 19  compliment_funny    int64
 20  compliment_writer   int64
 21  compliment_photos   int64
dtypes: float64(1), int64(16), object(5)
memory usage: 353.4+ MB

In [16]:
print(user_003.describe())

       review_count        useful         funny          cool          fans  \
count  2.105597e+06  2.105597e+06  2.105597e+06  2.105597e+06  2.105597e+06
mean   2.846875e+01  5.516853e+01  2.267667e+01  3.143013e+01  1.913746e+00
std    1.042146e+02  7.388068e+02  4.628811e+02  6.379274e+02  2.436510e+01
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
25%    2.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
50%    6.000000e+00  3.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
75%    1.900000e+01  1.500000e+01  3.000000e+00  4.000000e+00  0.000000e+00
max    1.747300e+04  2.062960e+05  1.858230e+05  1.998780e+05  1.249700e+04

       average_stars  compliment_hot  compliment_more  compliment_profile  \
count   2.105597e+06    2.105597e+06     2.105597e+06        2.105597e+06
mean    3.641863e+00    2.444596e+00     3.968618e-01        2.532631e-01
std     1.159519e+00    7.963704e+01     1.405658e+01        1.767698e+01
min     1.000000e+00    0.000000e+00     0.000000e+00        0.000000e+00
25%     3.000000e+00    0.000000e+00     0.000000e+00        0.000000e+00
50%     3.880000e+00    0.000000e+00     0.000000e+00        0.000000e+00
75%     4.500000e+00    0.000000e+00     0.000000e+00        0.000000e+00
max     5.000000e+00    2.578400e+04     1.350100e+04        1.418000e+04

       compliment_cute  compliment_list  compliment_note  compliment_plain  \
count     2.105597e+06     2.105597e+06     2.105597e+06      2.105597e+06
mean      1.858665e-01     9.631663e-02     1.921464e+00      4.124809e+00
std       1.170051e+01     1.049796e+01     6.177753e+01      1.364953e+02
min       0.000000e+00     0.000000e+00     0.000000e+00      0.000000e+00
25%       0.000000e+00     0.000000e+00     0.000000e+00      0.000000e+00
50%       0.000000e+00     0.000000e+00     0.000000e+00      0.000000e+00
75%       0.000000e+00     0.000000e+00     0.000000e+00      0.000000e+00
max       1.365400e+04     1.266900e+04     5.903100e+04      1.010970e+05

       compliment_cool  compliment_funny  compliment_writer  compliment_photos
count     2.105597e+06      2.105597e+06       2.105597e+06       2.105597e+06
mean      3.805567e+00      3.805567e+00       1.459133e+00       1.499514e+00
std       1.057484e+02      1.057484e+02       3.676692e+01       9.607754e+01
min       0.000000e+00      0.000000e+00       0.000000e+00       0.000000e+00
25%       0.000000e+00      0.000000e+00       0.000000e+00       0.000000e+00
50%       0.000000e+00      0.000000e+00       0.000000e+00       0.000000e+00
75%       0.000000e+00      0.000000e+00       0.000000e+00       0.000000e+00
max       4.996700e+04      4.996700e+04       1.593400e+04       8.263000e+04

In [17]:
print(user_003.isnull().sum())

user_id               0
name                  0
review_count          0
yelping_since         0
useful                0
funny                 0
cool                  0
elite                 0
friends               0
fans                  0
average_stars         0
compliment_hot        0
compliment_more       0
compliment_profile    0
compliment_cute       0
compliment_list       0
compliment_note       0
compliment_plain      0
compliment_cool       0
compliment_funny      0
compliment_writer     0
compliment_photos     0
dtype: int64